name: Pull Request Check
on:
    pull_request:
jobs:
 test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, nightly]
    steps:
      - uses: hecrj/setup-rust-action@v2
        with:
          rust-version: ${{ matrix.rust }}
      - uses: actions/checkout@master
      - name: Run tests
        run: cargo test --verbose